use critter_chronology;
INSERT INTO EMPLOYEE_SKILL(skill) VALUES ('PETTING');
INSERT INTO EMPLOYEE_SKILL(skill) VALUES ('WALKING');
INSERT INTO EMPLOYEE_SKILL(skill) VALUES ('FEEDING');
INSERT INTO EMPLOYEE_SKILL(skill) VALUES ('MEDICATING');
INSERT INTO EMPLOYEE_SKILL(skill) VALUES ('SHAVING');